name: Ashley Smalls
favicon: null
layout_spectrum: 0.8878472661599517
typography_spectrum: 0.512766654137522
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8442853917367756
  lightness: 0.7455549084115773
  saturation: 0.5688391414005309
  rhythmicContrast: 0.48227854422293603
purpose: []
